### ISSUE TITLE
dv.pages() does not work when combining folders with tags

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Calendar#29]
The following syntax for `dv.pages()` gives the errors as follows.

`pages: "dv.pages('(#ToDo or #Task) and -"Templates"').file.tasks.where()"`

On the other hand, the syntax works fine for other DataviewJS queries.

```
Evaluation Error: SyntaxError: Unexpected number
    at DataviewInlineApi.eval (plugin:dataview:19673:21)
    at evalInContext (plugin:dataview:19674:7)
    at asyncEvalInContext (plugin:dataview:19681:16)
    at DataviewJSRenderer.render (plugin:dataview:19705:19)
    at DataviewJSRenderer.onload (plugin:dataview:19289:14)
    at DataviewJSRenderer.e.load (app://obsidian.md/app.js:1:852364)
    at t.e.addChild (app://obsidian.md/app.js:1:852765)
    at t.addChild (app://obsidian.md/app.js:1:1246250)
    at Object.addChild (app://obsidian.md/app.js:1:1245275)
    at DataviewApi.executeJs (plugin:dataview:20214:19)
```

**Comment by 702573N** [comment]
It will take a while to understand why the query does not work like this. Since the snippet was implemented entirely with dataview, all the dv.pages() queries that are permitted and executable with dataview should also work with the Tasks calendar. The problem is probably caused by the quotation marks. But as I said, I'll have to take a look at this at some point.

To solve your problem, I have formulated the query a little more precisely and thus a little more extensively. This query works in my vault, so hopefully also in yours:

```
pages: "dv.pages().file.where(f=>f.tags.includes('#ToDo') || f.tags.includes('#Task')).where(f=>f.folder != 'Inbox').tasks"
```

**Comment by wenlzhang** [comment]
> This query works in my vault, so hopefully also in yours:

It also works for me. Thanks!
